name: example
description: "An example Flutter project using the dartblock_code package."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  google_fonts: ^8.0.0
  json_annotation: ^4.9.0
  dartblock_code:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - assets/dartblockEvaluatorSamples/
    - assets/dartblockSamples/
