name: dartblock_code
description: "Block-based programming framework 'DartBlock' primarily designed for mobile devices. Supports automatic evaluation, on-device execution and exception-throwing."
version: 1.2.0
repository: https://github.com/aryobarzan/dartblock

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.9.0
  code_text_field: ^1.1.0
  collection: ^1.17.1
  file_picker: ^10.3.7
  flutter_highlight: ^0.7.0
  google_fonts: ^6.3.2
  highlight: ^0.7.0
  json_annotation: ^4.9.0
  reorderables: ^0.6.0
  uuid: ^4.5.2
  flutter_riverpod: ^2.6.1

dev_dependencies:
  analyzer: ^9.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.3
flutter:
  assets:
    - assets/icons/

# Supported platforms:
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: "The main DartBlock widget for viewing and editing a program."
    path: screenshots/editor.jpg
  - description: "The console output after executing a DartBlock program."
    path: screenshots/console.jpg
  - description: "The Java version of a DartBlock program."
    path: screenshots/java.jpg
  - description: "Setting up evaluation schemas for a DartBlock program."
    path: screenshots/evaluator.jpg
  - description: "The automatic evaluation result for an input program based on a sample solution program and a set of evaluation schemas."
    path: screenshots/evaluation.jpg
  - description: "An exception thrown during execution, with its details displayed in the console."
    path: screenshots/exception_in_console.jpg

topics:
  - block-based
  - code
  - programming
  - editor
